name: sized_ints
description: A cross-library for fixed-size signed and unsigned ints 
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  spec: ^0.2.3
  test: ^1.24.0
