name: sized_ints
description: A cross-platform library for fixed-size signed and unsigned ints 
version: 0.1.0
repository: https://github.com/toddobryan/sized_ints

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.1.1
  spec: ^0.2.3
  test: ^1.24.0
